# Generated by Django 2.2.1 on 2019-09-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='description_long',
        ),
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='description_short',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.CharField(default='https://github.com/rmiyahara', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
