# Used to save database for skills
from main_page.models import Skill

s1 = Skill( language = 'C++')
s1.save()
s1 = Skill( language = 'C')
s1.save()
s1 = Skill( language = 'Arduino Programming')
s1.save()
s1 = Skill( language = 'Python')
s1.save()
s1 = Skill( language = 'HTML/CSS')
s1.save()
s1 = Skill( language = 'React')
s1.save()
s1 = Skill( language = 'Flask')
s1.save()
s1 = Skill( language = 'uWSGI/NGINX')
s1.save()
s1 = Skill( language = 'Django')
s1.save()
s1 = Skill( language = 'Lisp')
s1.save()
s1 = Skill( language = 'MongoDB')
s1.save()